# Generated by Django 2.1.5 on 2022-03-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20220303_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
